version: '3.7'

services:

  swagger:
    image: swaggerapi/swagger-ui:v3.22.1
    volumes:
      - ./swagger:/code
    ports:
      - "8001:8080"
    environment:
      SWAGGER_JSON: /code/openapi.yaml
      
networks:
  default:
    name: ${DOCKER_DEFAULT_NETWORK}